In [8]:
import nltk
nltk.download('punkt')  


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [23]:
#Tokenization Example

corpus = '''Hello, this is Rahul. I am learning NLP!
Please do support me.
'''
print(corpus)

Hello, this is Rahul. I am learning NLP!
Please do support me.



In [24]:
from nltk.tokenize import sent_tokenize   #sent_tokenize will help us convert paragraphs into sentences
sentences = sent_tokenize(corpus)
print(sentences)



['Hello, this is Rahul.', 'I am learning NLP!', 'Please do support me.']


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...


['Hello, this is Rahul.', 'I am learning NLP.']


[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


In [25]:
#to iterate through these sentences

for sentence in sentences:
    print(sentence)

Hello, this is Rahul.
I am learning NLP!
Please do support me.


In [26]:
#word tokenize
from nltk.tokenize import word_tokenize

words = word_tokenize(corpus)
print(words)

['Hello', ',', 'this', 'is', 'Rahul', '.', 'I', 'am', 'learning', 'NLP', '!', 'Please', 'do', 'support', 'me', '.']


In [27]:
for word in words:
    print(word)

Hello
,
this
is
Rahul
.
I
am
learning
NLP
!
Please
do
support
me
.


In [ ]:
from nltk.tokenize import TreebankWordTokenizer             #with the help of TreeBankTkn full stops wont be treated as separate words.

tokenizer = TreebankWordTokenizer()
tokenizer.tokenize(corpus)

['Hello',
 ',',
 'this',
 'is',
 'Rahul.',
 'I',
 'am',
 'learning',
 'NLP',
 '!',
 'Please',
 'do',
 'support',
 'me',
 '.']

In [31]:
from nltk.stem import PorterStemmer

words = ['goes','going','shopping','shop','however','history']

#create an object first
stemming = PorterStemmer()

#iterating
for word in words:
    print(word+"--->"+stemming.stem(word))       #we have to use the stem() with the object

goes--->goe
going--->go
shopping--->shop
shop--->shop
however--->howev
history--->histori


In [34]:
from nltk.stem import RegexpStemmer

regx_stemmer = RegexpStemmer('ing$|es$|able$',min=4)   # $ at the end indicates to stem out ing which comes in end only
a = regx_stemmer.stem("understanding")
b = regx_stemmer.stem("ingunderstand")
c = regx_stemmer.stem("goes")
d = regx_stemmer.stem("eatable")

stem_list = [a,b,c,d]
print(stem_list)

['understand', 'ingunderstand', 'go', 'eat']


In [35]:
from nltk.stem import SnowballStemmer

snow_stem = SnowballStemmer('english')

for word in words:
    print(word+"-->"+snow_stem.stem(word))

goes-->goe
going-->go
shopping-->shop
shop-->shop
however-->howev
history-->histori


In [38]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...


True

In [ ]:
from nltk.stem import WordNetLemmatizer
#define a object
lemmatizer = WordNetLemmatizer()
words = ['goes','going','shopping','however','history',"walking"]

for word in words:
    print(word+"-->"+lemmatizer.lemmatize(word,pos = 'v'))         #Give the pos value

goes-->go
going-->go
shopping-->shop
however-->however
history-->history
walking-->walk


In [41]:
from  nltk.stem import PorterStemmer
from nltk.corpus import stopwords

import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [42]:
#to find the list of stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [44]:
paragraph = ''' The children were playing in the gardens while their parents watched happily. 
Some dogs were running around, chasing balls and barking loudly.
 It was one of the most joyful afternoons they had experienced in months.
'''

from nltk.tokenize import sent_tokenize   #sent_tokenize will help us convert paragraphs into sentences
sentences = sent_tokenize(paragraph)
print(sentences)

from nltk.stem import SnowballStemmer     #to use snowball stemming
snow_stem = SnowballStemmer('english')


[' The children were playing in the gardens while their parents watched happily.', 'Some dogs were running around, chasing balls and barking loudly.', 'It was one of the most joyful afternoons they had experienced in months.']


In [45]:
#Apply stopwards, filter then snowball stemming

for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])            #converting each sentences to words and assigning to variable words
    words = [snow_stem.stem(word) for word in words if word not in set(stopwords.words('english'))]     #set is used to collect values and remove duplicates
    sentences[i] = ' '.join(words) #all the converted list of words are made again into sentences with spaces between each words

In [46]:
sentences

['the children play garden parent watch happili .',
 'some dog run around , chase ball bark loud .',
 'it one joy afternoon experienc month .']

In [47]:
#applying lemmatization to the same paragraph

paragraph = ''' The children were playing in the gardens while their parents watched happily. 
Some dogs were running around, chasing balls and barking loudly.
 It was one of the most joyful afternoons they had experienced in months.
'''

from nltk.tokenize import sent_tokenize   #sent_tokenize will help us convert paragraphs into sentences
sentences = sent_tokenize(paragraph)
print(sentences)

from nltk.stem import WordNetLemmatizer     #to use snowball stemming
lemmatizer = WordNetLemmatizer()

[' The children were playing in the gardens while their parents watched happily.', 'Some dogs were running around, chasing balls and barking loudly.', 'It was one of the most joyful afternoons they had experienced in months.']


In [50]:
#Apply stopwards, filter then lemmatization

for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])            #converting each sentences to words and assigning to variable words
    words = [lemmatizer.lemmatize(word.lower(),pos = 'v') for word in words if word not in set(stopwords.words('english'))]     #set is used to collect values and remove duplicates
    sentences[i] = ' '.join(words) #all the converted list of words are made again into sentences with spaces between each words

In [51]:
sentences

['the child play garden parent watch happily .',
 'some dog run around , chase ball bark loudly .',
 'it one joyful afternoon experience month .']

In [52]:
paragraph = ''' The children were playing in the gardens while their parents watched happily. 
Some dogs were running around, chasing balls and barking loudly.
 It was one of the most joyful afternoons they had experienced in months.
'''

from nltk.corpus import stopwords
import nltk

sentences = nltk.sent_tokenize(paragraph)
print(sentences)



[' The children were playing in the gardens while their parents watched happily.', 'Some dogs were running around, chasing balls and barking loudly.', 'It was one of the most joyful afternoons they had experienced in months.']


In [60]:
import nltk

# For newer NLTK versions (post-3.8)
nltk.download('averaged_perceptron_tagger_eng')

# You still need these for your code
nltk.download('punkt')
nltk.download('stopwords')


[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [61]:
# Will find out the post_tag for each words

for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])            #converting each sentences to words and assigning to variable words
    words = [word for word in words if word not in set(stopwords.words('english'))]     #set is used to collect values and remove duplicates
    pos_tag = nltk.pos_tag(words)
    print(pos_tag)

[('The', 'DT'), ('children', 'NNS'), ('playing', 'VBG'), ('gardens', 'NNS'), ('parents', 'NNS'), ('watched', 'VBD'), ('happily', 'RB'), ('.', '.')]
[('Some', 'DT'), ('dogs', 'NNS'), ('running', 'VBG'), ('around', 'RB'), (',', ','), ('chasing', 'VBG'), ('balls', 'NNS'), ('barking', 'VBG'), ('loudly', 'RB'), ('.', '.')]
[('It', 'PRP'), ('one', 'CD'), ('joyful', 'JJ'), ('afternoons', 'NNS'), ('experienced', 'VBD'), ('months', 'NNS'), ('.', '.')]


In [66]:
import nltk
tokens = nltk.word_tokenize("Taj Mahal is a beautiful Monument")

# For pos_tag_sents, wrap tokens in another list
result = nltk.pos_tag_sents([tokens])
print(result)

[[('Taj', 'NNP'), ('Mahal', 'NNP'), ('is', 'VBZ'), ('a', 'DT'), ('beautiful', 'JJ'), ('Monument', 'NN')]]


In [67]:
"Taj Mahal is a beautiful Monument".split()

['Taj', 'Mahal', 'is', 'a', 'beautiful', 'Monument']

In [ ]:
nltk.download('maxent_ne_chunker')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping chunkers\maxent_ne_chunker.zip.


True

In [70]:
nltk.download('words')

[nltk_data] Downloading package words to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\words.zip.


True

In [3]:
paragraph = "The Effiel Tower was build by Thomas Effiel in 1989, August 31st and was worth arond 1 million dollars in Paris, France"
import nltk
sentences = nltk.word_tokenize(paragraph)
print(sentences)

['The', 'Effiel', 'Tower', 'was', 'build', 'by', 'Thomas', 'Effiel', 'in', '1989', ',', 'August', '31st', 'and', 'was', 'worth', 'arond', '1', 'million', 'dollars', 'in', 'Paris', ',', 'France']


In [4]:
tagged_words = nltk.pos_tag(sentences)

In [77]:
nltk.download('maxent_ne_chunker_tab')
nltk.download('words')  # ne_chunk needs this dictionary

[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping chunkers\maxent_ne_chunker_tab.zip.
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\FC316LE\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [5]:
import nltk
tree = nltk.ne_chunk(tagged_words)
print(tree)

(S
  The/DT
  (ORGANIZATION Effiel/NNP Tower/NNP)
  was/VBD
  build/VBN
  by/IN
  (PERSON Thomas/NNP Effiel/NNP)
  in/IN
  1989/CD
  ,/,
  August/NNP
  31st/CD
  and/CC
  was/VBD
  worth/JJ
  arond/RB
  1/CD
  million/CD
  dollars/NNS
  in/IN
  (GPE Paris/NNP)
  ,/,
  (GPE France/NNP))


In [ ]:
nltk.ne_chunk(tagged_words).draw()

In [27]:
import pandas as pd
text = pd.read_excel("spam.xlsx")
print(text)

     Label                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5568  spam  This is the 2nd time we have tried 2 contact u...
5569   ham              Will Ì_ b going to esplanade fr home?
5570   ham  Pity, * was in mood for that. So...any other s...
5571   ham  The guy did some bitching but I acted like i'd...
5572   ham                         Rofl. Its true to its name

[5573 rows x 2 columns]


In [28]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re
#object
ps = PorterStemmer()

corpus = []

for i in range(0,len(text)):
    review = re.sub('[^a-zA-z]',' ',text['Message'][i])          #ro access each rows in a column we use text[message][i]
    review = review.lower()
    review = review.split()           #splits sentences into rows
    review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)             #words are joined to form sentences
    corpus.append(review)


 


In [29]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [31]:
pip install scikit-learn

   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/8.7 MB 12.6 MB/s eta 0:00:01
   -------- ------------------------------- 1.8/8.7 MB 4.6 MB/s eta 0:00:02
   --------- ------------------------------ 2.1/8.7 MB 4.5 MB/s eta 0:00:02
   ------------- -------------------------- 2.9/8.7 MB 3.9 MB/s eta 0:00:02
   ------------- -------------------------- 2.9/8.7 MB 3.9 MB/s eta 0:00:02
   ---------------- ----------------------- 3.7/8.7 MB 3.4 MB/s eta 0:00:02
   --------------------- ------------------ 4.7/8.7 MB 3.3 MB/s eta 0:00:02
   ---------------------- ----------------- 5.0/8.7 MB 3.3 MB/s eta 0:00:02
   ---------------------- ----------------- 5.0/8.7 MB 3.3 MB/s eta 0:00:02
   ------------------------ --------------- 5.2/8.7 MB 2.7 MB/s eta 0:00:02
   ------------------------- -------------- 5.5/8.7 MB 2.5 MB/s eta 0:00:02
   --------------------------- ------------ 6.0/8.7 MB 2.4 MB/s eta 0:00:02
   ---------------

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,binary=True)                      #maxfeatures indicate to pick the top2500 most occuring words, rest values are not required
                                                                        #binary BOW we make binary as true

In [ ]:
X = cv.fit_transform(corpus).toarray()                        #max=2500, we are going to have 2500 columsn
X.shape                      #to view the size taken

(5573, 2500)

In [35]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5573, 2500))

In [36]:
cv.vocabulary_

{'go': np.int64(860),
 'point': np.int64(1592),
 'crazi': np.int64(451),
 'avail': np.int64(146),
 'bugi': np.int64(279),
 'great': np.int64(895),
 'world': np.int64(2435),
 'la': np.int64(1162),
 'cine': np.int64(371),
 'got': np.int64(880),
 'wat': np.int64(2365),
 'ok': np.int64(1479),
 'lar': np.int64(1170),
 'joke': np.int64(1125),
 'wif': np.int64(2403),
 'oni': np.int64(1487),
 'free': np.int64(769),
 'entri': np.int64(619),
 'wkli': np.int64(2424),
 'comp': np.int64(406),
 'win': np.int64(2407),
 'fa': np.int64(662),
 'cup': np.int64(465),
 'final': np.int64(711),
 'tkt': np.int64(2210),
 'st': np.int64(2054),
 'may': np.int64(1308),
 'text': np.int64(2169),
 'receiv': np.int64(1753),
 'question': np.int64(1705),
 'std': np.int64(2065),
 'txt': np.int64(2267),
 'rate': np.int64(1730),
 'appli': np.int64(104),
 'dun': np.int64(580),
 'say': np.int64(1885),
 'earli': np.int64(584),
 'hor': np.int64(1006),
 'alreadi': np.int64(72),
 'nah': np.int64(1416),
 'think': np.int64(2184),

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=700,binary=True,ngram_range=(1,2))                      #maxfeatures indicate to pick the top2500 most occuring words, rest values are not required
X = cv.fit_transform(corpus).toarray()   
cv.vocabulary_
                                                   

{'go': np.int64(233),
 'point': np.int64(459),
 'avail': np.int64(31),
 'great': np.int64(246),
 'world': np.int64(680),
 'got': np.int64(244),
 'wat': np.int64(651),
 'ok': np.int64(414),
 'lar': np.int64(313),
 'joke': np.int64(302),
 'wif': np.int64(667),
 'free': np.int64(211),
 'entri': np.int64(182),
 'wkli': np.int64(675),
 'win': np.int64(670),
 'final': np.int64(198),
 'st': np.int64(555),
 'may': np.int64(358),
 'text': np.int64(581),
 'receiv': np.int64(489),
 'question': np.int64(478),
 'txt': np.int64(619),
 'rate': np.int64(482),
 'appli': np.int64(25),
 'free entri': np.int64(213),
 'dun': np.int64(169),
 'say': np.int64(510),
 'earli': np.int64(171),
 'alreadi': np.int64(13),
 'think': np.int64(587),
 'goe': np.int64(236),
 'live': np.int64(335),
 'around': np.int64(27),
 'though': np.int64(590),
 'freemsg': np.int64(215),
 'hey': np.int64(272),
 'week': np.int64(655),
 'word': np.int64(678),
 'back': np.int64(39),
 'like': np.int64(331),
 'fun': np.int64(223),
 'still'

In [39]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
#object
wordlemmatize = WordNetLemmatizer()

corpus = []

for i in range(0,len(text)):
    review = re.sub('[^a-zA-z]',' ',text['Message'][i])          #ro access each rows in a column we use text[message][i]
    review = review.lower()
    review = review.split()           #splits sentences into rows
    review = [wordlemmatize.lemmatize(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)             #words are joined to form sentences
    corpus.append(review)

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = CountVectorizer(max_features=100)
X = tf.fit_transform(corpus).toarray()

In [42]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,formatter = dict(float = lambda x: "%.3g" % x ))  

In [47]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [119]:
#Load the dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()                     #displays the first 5 rows

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [120]:
## Data preprocessing
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)       #dropiing irelevant columns from data, axis =1 means columnwise
data

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [121]:
#Encode categorical variables
label_encoder_gender = LabelEncoder()                     #This is used from sklearn, used to encode values as 0 or 1 in gender as it has only 2 values
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])      #fit_transform studies the values and transforms here into numerical value
data 

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [122]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geo = OneHotEncoder()

geo_encoder = one_hot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [124]:
#Now convert it into a matrix
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [125]:
one_hot_encoder_geo.get_feature_names_out(['Geography'])    #This allows us to see which all values has been OHE

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [126]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(),columns=one_hot_encoder_geo.get_feature_names_out(['Geography']) )
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [127]:
#Combine onehot encoded values with original data

data = pd.concat([data.drop('Geography',axis =1),geo_encoded_df],axis=1)
data.head()

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [128]:
#Save encoders and scalars cerated in a pickle file

with open('label_encoder_gender.pkl','wb') as file:    #Creates a new .pkl file
    pickle.dump(label_encoder_gender,file)
with open('one_hot_encoder_geo.pkl','wb') as file:
    pickle.dump(one_hot_encoder_geo,file)

In [129]:
#Divide dataset into dependent and independent features

X = data.drop('Exited',axis=1)  #Independent
Y = data['Exited']   #Dependent

In [130]:
#Split data into training and testing
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

#Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [89]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [90]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(2000, 12))

In [131]:
#saving to pickle file

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [132]:
data

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [93]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [133]:
#Build the ANN Model

model = Sequential(
    [      #First hidden layer connected to input
        Dense(64,activation='relu',input_shape = (X_train.shape[1],)),  #X_train is used to train the data and shape[1],blank = number of features per sample. ",blank" takes all features
        Dense(32,activation='relu'), #HL2
        Dense(1,activation='sigmoid')  #Output layer
    ]
)

c:\Users\FC316LE\AppData\Local\miniconda3\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [134]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [135]:
#compile the model 1

model.compile(optimizer="adam",loss='binary_crossentropy',metrics=['accuracy'])        #for binary classification we use this and for multilevel we use sparse_entropy

In [136]:
#compile the model 2
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)                  #can define our own learning rate here previous case takes a default value
loss_model = tensorflow.keras.losses.BinaryCrossentropy()

model.compile(optimizer=opt,loss=loss_model,metrics=['accuracy'])  

In [137]:
## Setup tensor board
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_directory = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_directory,histogram_freq=1)

In [138]:
#Setup Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)  #be pateint for atleast 5 epochs and then do Early Stopping if needed

In [139]:
#Train the model
history = model.fit(
    X_train,Y_train,validation_data=(X_test,Y_test),epochs=100,
    callbacks = [tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8361 - loss: 0.3943 - val_accuracy: 0.8495 - val_loss: 0.3570
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8533 - loss: 0.3544 - val_accuracy: 0.8615 - val_loss: 0.3377
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8560 - loss: 0.3467 - val_accuracy: 0.8590 - val_loss: 0.3450
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8571 - loss: 0.3432 - val_accuracy: 0.8590 - val_loss: 0.3458
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8576 - loss: 0.3430 - val_accuracy: 0.8525 - val_loss: 0.3458
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8593 - loss: 0.3374 - val_accuracy: 0.8570 - val_loss: 0.3421
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8644 - loss: 0.3362 - val_accuracy: 0.8590 - val_loss: 0.3447
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8621 - loss: 0.3359 - val_accu

In [140]:
#saving this model
model.save('model.h5')

In [41]:
#Load TensorBoard Extension

%load_ext tensorboard

In [43]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 24884), started 0:01:02 ago. (Use '!kill 24884' to kill it.)

In [141]:
#Prediction
from tensorflow.keras.models import load_model

#load the trained model, pickle file, scalar, OHE
model = load_model('model.h5')

#load the encoder and scalar
with open('one_hot_encoder_geo.pkl','rb') as file:
    one_hot_encoder_geo = pickle.load(file)
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

In [142]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [143]:

geo_encoder = one_hot_encoder_geo.transform([[input_data['Geography']]]).toarray()  #OHE requires data in 2D, that is why 2 square brackets
df_encoded_geo = pd.DataFrame(geo_encoder,columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
df_encoded_geo

c:\Users\FC316LE\AppData\Local\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [144]:
input_df = pd.DataFrame([input_data])              #converting a dict to table
input_df

CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [145]:
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [146]:
#concat of OHE into input data

input_df = pd.concat([input_df.drop("Geography",axis=1),df_encoded_geo],axis=1)  #Whenever you want to concatenate multiple DataFrames, wrap them in a list
input_df

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [147]:
#concvertng into scalar values
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [148]:
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


array([[0.01597918]], dtype=float32)

In [149]:
prediction_prob = prediction[0][0]
prediction_prob

np.float32(0.01597918)

In [150]:
if prediction_prob > 0.5:
    print('The customer is likely to churn')
else:
    print('The customer is not likely to churn')

The customer is not likely to churn


In [167]:
## Word Embeddings
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

sent = ['a glass of milk',
        'the cup of tea',
        'I am a good boy',
        'the glass of juice'
]

In [168]:
sent

['a glass of milk', 'the cup of tea', 'I am a good boy', 'the glass of juice']

In [169]:
voc_size = 10000
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3638, 9936, 1036, 2076],
 [5094, 1395, 1036, 2157],
 [985, 2279, 3638, 1962, 4485],
 [5094, 9936, 1036, 5990]]

In [175]:
#Word Embeddings

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [171]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)

In [177]:
print(embedded_docs)

[[   0    0    0    0 3638 9936 1036 2076]
 [   0    0    0    0 5094 1395 1036 2157]
 [   0    0    0  985 2279 3638 1962 4485]
 [   0    0    0    0 5094 9936 1036 5990]]


In [178]:
#Feature Representation
dim =10
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length)) #Adding a Embedding Layer to our model
#train
model.compile('adam','mse')   #adam is the optimizer and loss function is mse

c:\Users\FC316LE\AppData\Local\miniconda3\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [181]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (4, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [180]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step


array([[[ 0.02646324, -0.01420127,  0.01776257, -0.01645806,
          0.01392288, -0.03266357,  0.03534045, -0.00140784,
          0.00197377, -0.01842197],
        [ 0.02646324, -0.01420127,  0.01776257, -0.01645806,
          0.01392288, -0.03266357,  0.03534045, -0.00140784,
          0.00197377, -0.01842197],
        [ 0.02646324, -0.01420127,  0.01776257, -0.01645806,
          0.01392288, -0.03266357,  0.03534045, -0.00140784,
          0.00197377, -0.01842197],
        [ 0.02646324, -0.01420127,  0.01776257, -0.01645806,
          0.01392288, -0.03266357,  0.03534045, -0.00140784,
          0.00197377, -0.01842197],
        [-0.01323009,  0.01165577, -0.04552482, -0.00890896,
         -0.02304286,  0.02990704,  0.01552539, -0.01223302,
         -0.04284222,  0.03085187],
        [-0.04864476, -0.01736289,  0.04796194,  0.02112206,
          0.04908483, -0.00840663,  0.00845854,  0.02431414,
          0.01154106, -0.0079723 ],
        [-0.01527905,  0.04388886, -0.00275927,  0.0

In [3]:
#IMDB Project

import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense

In [4]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context


In [13]:

import truststore
truststore.inject_into_ssl()


In [12]:
#load data
from tensorflow.keras.datasets import imdb  
max_features = 10000   #vocab size
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=max_features)

print(f'The training data shape : {X_train},Training labels shape :{y_train}')
print(f'The training data shape : {X_test},Training labels shape :{y_test}')

Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/imdb.npz: None -- [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1028)